### PR TITLE
:sparkles: Output config for GitHub Actions

### PR DESCRIPTION
**Pull request by joaofouyer**
Outputs the Qodana Scan summary so workflows can use it.

### CODE REVIEW

**Comment by tiulpin** [comment]
@joaofouyer could you please provide any real world example? Will be glad to merge it (hint: you can run the action by referencing it from your own repo –` joaofouyer/qodana-action@github-action/output`

**Comment by tiulpin** [comment]
GitHub won't allow me to share the creds for Qodana analysis with you, but I can see every pipeline is OK, so feel free to ignore it in this PR.

**Comment by joaofouyer** [comment]
I'm currently working on an example in which I use the output to generate coverage badges and a button with a link to the Qodana Report. This will allow me to incorporate these elements into the project's README.

Initially, my approach was to generate the badge within the Qodana Action itself. However, I realized that this would require adding new action inputs, and the feature of generating badges might not be desired by many users.

Hence, I decided to output the summary instead, which can be used by another action to create badges. This change should have a minimal impact on the current behavior.

As soon as I have a working example of the use of output I'll link in this PR.

**Comment by tiulpin** [comment]
I'm closing this for now, as it seems to be a forgotten pull request. Feel free to reopen/make a new one if you wish. Thank you!

**Pull request closed without merging**
